### ISSUE TITLE
Cannot remove last time log

### ISSUE THREAD

**Issue by rbugajewski** [hicknhack-software/redmine_time_tracker#104]
I have a time log that I cannot remove. When I right click on the entry and select “Delete” I get the following error message:

> Updating time log would result in negative bookable time. Not allowed!

This is the last not booked time log entry. Shouldn’t I be allowed to just delete it? Could it be that there’s somewhere a comparison to `< 0` instead of `<= 0`?

**Comment by jume-dev** [comment]
This is fixed in the [new version](https://github.com/hicknhack-software/redmine_hourglass) by forcing a 1 to 1 connection between logs and bookings.
