### ISSUE TITLE
Sugestion: auto start/stop

### ISSUE THREAD

**Issue by lfantinel** [hicknhack-software/redmine_time_tracker#113]
1. change status automatically on start/stop timer
2. start/stop timer automatically on status change to especific or closed status

thanks

**Comment by jume-dev** [comment]
I guess this feature needs some revisiting, especially cause the [new plugin version](https://github.com/hicknhack-software/redmine_hourglass) supports project specific settings. It's tracked in hicknhack-software/redmine_hourglass#1
