### ISSUE TITLE
Always use fixed Filters for Overview page

### ISSUE THREAD

**Issue by arBmind** [hicknhack-software/redmine_time_tracker#142]
Currently the filters from the session are preferred. If I change the filter on the Time Entry or Time Bookings Tab, the overview will use them as well.

I would expect to see only Time Entries and Time Bookings from the starting day of last week (a Redmine Account Setting). And always use the Default Columns and Grouping.

A further enhancement would be to show the total time for filtered groups.

**Comment by jume-dev** [comment]
This is fixed in the [new version](https://github.com/hicknhack-software/redmine_hourglass).
