### ISSUE TITLE
Use better Icons

### ISSUE THREAD

**Issue by mstarke** [hicknhack-software/redmine_time_tracker#146]
There are a couple of icons that can be replaced by better suiting ones. Redmine uses this icon set http://www.famfamfam.com/lab/icons/silk/

continue tracking: ![time_go](http://www.famfamfam.com/lab/icons/silk/icons/time_go.png) (time_go.png)
book timing: ![time_add](http://www.famfamfam.com/lab/icons/silk/icons/time_add.png) (time_add.png)

**Comment by jume-dev** [comment]
time_add is already used for starting timers, i hesitate to use it also for booking, but i agree with the continue tracking icon change (if we readd this feature ;) )

We have added proper title tags in the [new version](https://github.com/hicknhack-software/redmine_hourglass).
