### ISSUE TITLE
Start/Stop Timetracker in Menu via asynchronous request

### ISSUE THREAD

**Issue by mstarke** [hicknhack-software/redmine_time_tracker#149]
If one edits a Ticket and then decides to start the Time Tracker via the Menu, the form might get lost due to a reload.

If this is an edge case, then it might not be worth changing the structure

**Comment by jume-dev** [comment]
This is kinda fixed in the [new version](https://github.com/hicknhack-software/redmine_hourglass). You will now be messaged if you want to leave the page. This could be further improved to use ajax i guess.
