### ISSUE TITLE
Close gap between timers after rounding down

### ISSUE THREAD

**Issue by mstarke** [hicknhack-software/redmine_time_tracker#152]
If the user stops the time an the time log will be shortened due to rounding down there is a gap that losses time atually spent working.

Possible solution: If rounding is enabled and a time is started inside the rounding interval next to a previous log entry, snap the start time to the previous time entry and thus prevent any gaps.

**Comment by jume-dev** [comment]
This is fixed in the [new version](https://github.com/hicknhack-software/redmine_hourglass).
