### ISSUE TITLE
Add a "Delete Tracker" Button in tt_overview

### ISSUE THREAD

**Issue by mstarke** [hicknhack-software/redmine_time_tracker#153]
If a tracker is running, you can delete it in the tracker-overview (given the permission are set) it would be nice to have the "delete" button present at the active tracker, if permissions allow to delete the tracker so it's faster than to switch tab and delete the tracker.

**Comment by jume-dev** [comment]
This is added in the [new version](https://github.com/hicknhack-software/redmine_hourglass).
