### ISSUE TITLE
Add filter option and column for under/over estimated times on issues

### ISSUE THREAD

**Issue by mstarke** [hicknhack-software/redmine_time_tracker#157]
It's very helpful to see what issues where under estimated and which were overestimated. It would be nice to:
1. Have the option for a column to show "time left until estimate reached"
2. Have a filter for over/under estimated issues

**Comment by jume-dev** [comment]
I guess you mean to have this in the issue list, right? If not i don't see how we ever could implement this properly.
But for the issues this would be a nice addition, we can add this to our [new version](https://github.com/hicknhack-software/redmine_hourglass)
