### ISSUE TITLE
Exclude non work hours

### ISSUE THREAD

**Issue by asmikhailov** [hicknhack-software/redmine_time_tracker#165]
Is it possible improve time_tracker with excluding non working hours from tracked time on issue?
For example hours from 7 pm til 7 am now working hours for me, but if i didn't stop timer manually it keep counting time through all night.

**Comment by jume-dev** [comment]
I don't think that is a feature to implement in the website itself. Too much to have settings needed for.
But with the [new versions](https://github.com/hicknhack-software/redmine_hourglass) api, one could build a desktop client like toggl has one, which takes note when you close/shutdown your pc and act accordingly.
