### ISSUE TITLE
Add comment field to time booking of ticket related tracker aka. revert your additions

### ISSUE THREAD

**Issue by tvdeyen** [hicknhack-software/redmine_time_tracker#176]
As a user that started a time tracker for an particular issue, I want to enter a comment while booking the time.

![add-comment-to-time-booking](https://cloud.githubusercontent.com/assets/42868/3355096/3e9936c2-faae-11e3-8629-98b9a7d862a8.jpg)

Or **even better revert the behaviour to the old one**, before you forked and took over the development of this plugin:

After stopping the time tracker just redirect to the **standard redmine time booking form**. So you don't need to add any extra fancy javascript dialogs and duplicate the redmine booking form.

Why did you changed this behaviour anyway? I really must say, that you made too much changes to this plugin. Reports are nice and such, but duplicating the default redmine behaviour just to have a fancy booking dialog is too much IHMO.

_Please consider to revert these changes back to the default and well known behaviour._

**Comment by jume-dev** [comment]
While we don't have that feature implemented yet, we have a [new version](https://github.com/hicknhack-software/redmine_hourglass) of this plugin, where it will be way easier to add such behavior. I created an issue there for time entry custom fields .

About that booking dialog, i am not sure, if we really want this. I don't like that dialog, but it was needed cause activities are mandatory. So ideally we would replace that dialog with another solution, not sure whch though. If you some how still want this and have an idea, feel free to create an issue in the new repo.
