### ISSUE TITLE
Missing functionality (Feature permission)

### ISSUE THREAD

**Issue by purell** [hicknhack-software/redmine_time_tracker#179]
I don't know if this feature is already exists but could it be possible to allow the user to ONLY start timer on it's assigned issues and PREVENT him to start global timer and stop it without any bookable time result ?

In other word, is there a way that user can ONLY do BOOKABLE time.

Best regards,

**Comment by jume-dev** [comment]
We continue thinking about this in hicknhack-software/redmine_hourglass#7
