### ISSUE TITLE
Allow admins to change user of a timetracking

### ISSUE THREAD

**Issue by arBmind** [hicknhack-software/redmine_time_tracker#181]
Administrators currently are not allowed to create time tracking on the behalf of other members.

A use case is a trip to a customer with some employees, without using regular time tracking. Each employee has to create the respective time tracking entries, and the administrator can change them to the time slot of the trip.

Please add an option to allow administrators the creation of time tracking entries for users. Or let them change the user in existing time tracking entries.

**Comment by jume-dev** [comment]
This is added in the [new version](https://github.com/hicknhack-software/redmine_hourglass).
