### ISSUE TITLE
Timer does not recognize removal of bookings

### ISSUE THREAD

**Issue by mstarke** [hicknhack-software/redmine_time_tracker#185]
The timer waits after it was started for a dedicated start-time if a booking was rounded up so it stopped "in the future". If this booking is removed, the timer should start immediately as it now does not collide with any booking any more.

**Comment by jume-dev** [comment]
The [new version](https://github.com/hicknhack-software/redmine_hourglass) changed the behaviour so that this won't happen anymore, because time logs are not rounded anymore, but only bookings are.
