### ISSUE TITLE
Complete Rewrite

### ISSUE THREAD

**Issue by jume-dev** [hicknhack-software/redmine_time_tracker#194]
At the moment i am working on a complete rewrite of the this plugin. It will be loosely based on our existing work, but in the end hopefully be more useful.
Plan is also to increase the code quality heavily as good as it is possible with a redmine based plugin.
You can keep track on my progress on the rewrite branch. Feedback and contributions are always welcome.

**Comment by kusmierz** [comment]
Any news here?

**Comment by arBmind** [comment]
Sorry we got busy with earning money for christmas.
I hope that we have the time to get back to this in February next year.

You may take a look at the branch.
Contributions and pull requests are always welcome!

**Comment by jume-dev** [comment]
Rewrite is done at [Redmine Hourglass](https://github.com/hicknhack-software/redmine_hourglass). We are close to releasing the new 1.0.0 version, just some internal testing needed.
