### ISSUE TITLE
Start and Stop tracking via context menu in issue table not working properly

### ISSUE THREAD

**Issue by sn3ek** [hicknhack-software/redmine_time_tracker#195]
I have assigned a tracking session to a specific issue. Now I want to start the time tracker on a different issue and therefor want to stop the old session. This causes a problem when the activity for the first tracker session is not defined (developing, planing, ...). Then the second tracker will not start after the first one has stopped.

**Comment by jume-dev** [comment]
We removed the continue feature in the [new version](https://github.com/hicknhack-software/redmine_hourglass) for now, so this won't be a problem anymore ;)

If you need this feature consider giving your opinion [here](hicknhack-software/redmine_hourglass#3)
