### ISSUE TITLE
Redmine 3.0 Support

### ISSUE THREAD

**Issue by aledr** [hicknhack-software/redmine_time_tracker#196]
Hi there!

Are you already thinking about Redmine 3.0 support?
Here is what I get:

Starting Time Tracker plugin for RedMine
Started GET "/tt_overview" for 177.92.56.134 at 2015-03-07 01:41:11 -0300
Processing by TtOverviewController#index as HTML
  Current user: aledr (id=68)
Completed 500 Internal Server Error in 77ms

ArgumentError (The scope body needs to be callable.):
 ...

------------------------------------

Started GET "/tt_overview" for 177.92.56.134 at 2015-03-07 01:53:40 -0300
Processing by TtOverviewController#index as HTML
  Current user: aledr (id=68)
Completed 500 Internal Server Error in 62ms

NoMethodError (undefined method `auth_values' for #<TimeLogQuery:0x00000004e05958>):
  app/models/query.rb:353:in `available_filters'
  app/models/query.rb:242:in `build_from_params'

------------------------------------

Thanks.

**Comment by jume-dev** [comment]
Hey,
we haven't talked about that yet, but we will support redmine 3. I'll check it, when i find the time for it,
iMeanwhile feel free to submit a pull request :)

**Comment by aledr** [comment]
Really would like to, but no Ruby knowledgement.

**Comment by amachu** [comment]
Would like the same at the earliest. Will try from my end too.

**Comment by tobiasgoecke** [comment]
bundle exec rake redmine:plugins NAME=redmine_time_tracker RAILS_ENV=production
An error occurred while loading the routes definition of redmine_time_tracker plugin (/opt/bitnami/apps/redmine/htdocs/plugins/redmine_time_tracker/config/routes.rb): uninitialized constant ActionController::Routing.

**Comment by Bolik** [comment]
+1

**Comment by Reeslo** [comment]
+2

**Comment by tbraun89** [comment]
I've added support for Redmine Version 3.0.4 and 3.1.0 in the current master branch, this should be fixed.

**Comment by Reeslo** [comment]
:+1:

**Comment by Reeslo** [comment]
:+1:
