### ISSUE TITLE
it doesn't install with redmine 2.6.x

### ISSUE THREAD

**Issue by mmiat** [hicknhack-software/redmine_time_tracker#197]
# rake redmine:plugins:redmine_time_tracker:install RAILS_ENV=production

(in /var/www/redmine)
[DEPRECATION] requiring "RMagick" is deprecated. Use "rmagick" instead
## Compiling coffeescript files:

rake aborted!
NameError: uninitialized constant CoffeeScript
/var/www/redmine/plugins/redmine_time_tracker/lib/tasks/setup_plugin.rake:91:in `convert_file'
/var/www/redmine/plugins/redmine_time_tracker/lib/tasks/setup_plugin.rake:48:in`block (7 levels) in <top (required)>'
/var/www/redmine/plugins/redmine_time_tracker/lib/tasks/setup_plugin.rake:47:in `each'
/var/www/redmine/plugins/redmine_time_tracker/lib/tasks/setup_plugin.rake:47:in`block (6 levels) in <top (required)>'
/var/www/redmine/plugins/redmine_time_tracker/lib/tasks/setup_plugin.rake:46:in `each'
/var/www/redmine/plugins/redmine_time_tracker/lib/tasks/setup_plugin.rake:46:in`block (5 levels) in <top (required)>'
/var/www/redmine/plugins/redmine_time_tracker/lib/tasks/setup_plugin.rake:13:in `block (4 levels) in <top (required)>'
Tasks: TOP => redmine:plugins:redmine_time_tracker:convert:coffeescript
(See full trace by running task with --trace)

**Comment by MDXDave** [comment]
+1

**Comment by jume-dev** [comment]
Hmm, strange one, because our travis tries with redmine 2.6.0 and this works.
As it seems it is a problem with coffeescript. Please check if the Coffeescript gem is installed and in which version

**Comment by mmiat** [comment]
my redmine is 2.6.3.stable
my coffee-script is 2.4.1
my coffee-script-source is 1.9.1.1

**Comment by gartorware** [comment]
Same problem here, same gem versions

**Comment by vvklymchuk** [comment]
I use Redmine 3.2.0 and the same error.
As described here http://stackoverflow.com/questions/28312460/object-doesnt-support-this-property-or-method-rails-windows-64bit
in the second answer, I downgraded coffe-script-source to 1.8.0 and the plugin was installed successfully
