### ISSUE TITLE
Mobile-App for Android

### ISSUE THREAD

**Issue by suther** [hicknhack-software/redmine_time_tracker#200]
Is there a way to create a mobile-App for Android, to use this TimeTracker (start, stop...)
Does the Timetracker have an API ?

**Comment by arBmind** [comment]
As far as I can see, we currently do not have a full API for that.
But it should be quite easy to build one.
The `time_trackers_controller.rb` contains all the logic you need.

**Comment by jume-dev** [comment]
The [new version](https://github.com/hicknhack-software/redmine_hourglass) is fully based on an api, so it should be easy to create a android app. Sadly i hadn't time to properly document the api yet, but it's working and you can use it already. Take a look in [app/controllers/hourglass](https://github.com/hicknhack-software/redmine_hourglass/tree/master/app/controllers/hourglass) for available methods.
