### ISSUE TITLE
Add additional fields to printout

### ISSUE THREAD

**Issue by mstarke** [hicknhack-software/redmine_time_tracker#201]
There are two fields that should be added to the print out below the "overall time" next to the bar chart:
- validated by <name>, <date>
- acknowledge/approved by <name>,<date>

The first field is for the person that booked the hours to commit to the bookings, or for a representative
The second field is for the client to signal it's ok and thus allow the hours to be billed.

**Comment by jume-dev** [comment]
Valid point, but i am not sure if we should simple include it like that or make it customizable. Let's continue our discussion on the new version: hicknhack-software/redmine_hourglass#6
