### ISSUE TITLE
Time logged after hours shows up on next day's Spent Time

### ISSUE THREAD

**Issue by danklassen** [hicknhack-software/redmine_time_tracker#206]
From what I can tell, it seems that any time booked after a certain time of day (I believe 5:00pm) shows up on the next day's Spent Time. The date correctly shows up on the time entry for the ticket when viewing the time details, however when viewing Spent Time on 'My Page' it does not show up until the following day.

The time zone on the server, my redmine user's time zone, and my local time zone are all the same if that helps out at all.

Let me know if there are any other details which would be helpful, or if this is intended behaviour. If it is intended, would it be possible to have a customizable cut-off time as we often work late and those hours show up on the next day.

Thanks for all your work! It really is appreciated.

**Comment by jume-dev** [comment]
Thanks for your kind words :)
If i am not mistaken, this is related to #101 and we are aware of it, but sadly we were never able to fix it properly.

So no, it is not intended, but a problem of inconsistent behavior between redmine and the timetracker.

For now, i can't do much for you. But if you feel a little lucky, you can try the rewrite branch and see if it fixes your problems. While it is near feature complete to the old implementation (only context menus are missing) and overall pretty stable, i can not guarantee that nothing happens to your data. So better do a backup before or try it first on an development database.

You need at least redmine version 3.0 and a ruby higher version 2.
Installation is basically the same as with the [old plugin](https://github.com/hicknhack-software/redmine_time_tracker#install), except the step 4 is not necessary.

Hit me up, if you have any problems.

**Comment by danklassen** [comment]
Thanks for the quick response. I have on my list to upgrade to Redmine 3+ at some point so this is extra incentive to do so. When I do have a chance to migrate over, I'll try running off of the rewrite branch and let you know if that takes care of things.

Thanks again

**Comment by jume-dev** [comment]
I am afraid this is not fixed in the [new version](https://github.com/hicknhack-software/redmine_hourglass) too, but i found a way we could fix this. I created an issue for this here: hicknhack-software/redmine_hourglass#5
