### ISSUE TITLE
Error in coffee-script

### ISSUE THREAD

**Issue by Sh4d0wF1gh7** [hicknhack-software/redmine_time_tracker#208]
Hello,

I try to install this on a redmine 3.3.0 environment but just get following errors:

```
rake aborted!
Bundler::GemRequireError: There was an error while trying to load the gem 'coffee-script'.
Gem Load Error is: Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes.
Backtrace for gem load error is:
/usr/lib/ruby/gems/1.9.1/gems/execjs-2.7.0/lib/execjs/runtimes.rb:58:in `autodetect'
/usr/lib/ruby/gems/1.9.1/gems/execjs-2.7.0/lib/execjs.rb:5:in `<module:ExecJS>'
/usr/lib/ruby/gems/1.9.1/gems/execjs-2.7.0/lib/execjs.rb:4:in `<top (required)>'
/usr/lib/ruby/gems/1.9.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/usr/lib/ruby/gems/1.9.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
/usr/lib/ruby/gems/1.9.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/lib/ruby/gems/1.9.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/usr/lib/ruby/gems/1.9.1/gems/coffee-script-2.4.1/lib/coffee_script.rb:1:in `<top (required)>'
/usr/lib/ruby/gems/1.9.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/usr/lib/ruby/gems/1.9.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
/usr/lib/ruby/gems/1.9.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/lib/ruby/gems/1.9.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/usr/lib/ruby/gems/1.9.1/gems/coffee-script-2.4.1/lib/coffee-script.rb:1:in `<top (required)>'
/usr/lib/ruby/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `require'
/usr/lib/ruby/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `block (2 levels) in require'
/usr/lib/ruby/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `each'
/usr/lib/ruby/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `block in require'
/usr/lib/ruby/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `each'
/usr/lib/ruby/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `require'
/usr/lib/ruby/gems/1.9.1/gems/bundler-1.12.5/lib/bundler.rb:102:in `require'
/var/www/redmine-3.3.0/config/application.rb:5:in `<top (required)>'
/usr/local/lib/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/lib/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:55:in `require'
/var/www/redmine-3.3.0/Rakefile:5:in `<top (required)>'
/usr/lib/ruby/gems/1.9.1/gems/rake-11.2.2/lib/rake/rake_module.rb:28:in `load'
/usr/lib/ruby/gems/1.9.1/gems/rake-11.2.2/lib/rake/rake_module.rb:28:in `load_rakefile'
/usr/lib/ruby/gems/1.9.1/gems/rake-11.2.2/lib/rake/application.rb:686:in `raw_load_rakefile'
/usr/lib/ruby/gems/1.9.1/gems/rake-11.2.2/lib/rake/application.rb:96:in `block in load_rakefile'
/usr/lib/ruby/gems/1.9.1/gems/rake-11.2.2/lib/rake/application.rb:178:in `standard_exception_handling'
/usr/lib/ruby/gems/1.9.1/gems/rake-11.2.2/lib/rake/application.rb:95:in `load_rakefile'
/usr/lib/ruby/gems/1.9.1/gems/rake-11.2.2/lib/rake/application.rb:79:in `block in run'
/usr/lib/ruby/gems/1.9.1/gems/rake-11.2.2/lib/rake/application.rb:178:in `standard_exception_handling'
/usr/lib/ruby/gems/1.9.1/gems/rake-11.2.2/lib/rake/application.rb:77:in `run'
/usr/lib/ruby/gems/1.9.1/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
Bundler Error Backtrace:
/var/www/redmine-3.3.0/config/application.rb:5:in `<top (required)>'
/var/www/redmine-3.3.0/Rakefile:5:in `<top (required)>'
(See full trace by running task with --trace)
```

**Comment by jume-dev** [comment]
Hi
If you read the message carefully:
>  Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes

You see, your problem is a missing javascript runtime. Go follow the link and select one to install.

**Comment by Sh4d0wF1gh7** [comment]
Hello,
i tried but it didn´t solve my problem. I installed Version ExecJS 2.7.0 successfully and its listed in the USING ones. but the error comes again, also after bundle update and retry bundle install which works.
LG

**Comment by jume-dev** [comment]
Did you install any runtime loke nodejs?

**Comment by Sh4d0wF1gh7** [comment]
So far no? Only the ExecJS i thought it will select one itself?

**Comment by jume-dev** [comment]
Well, yes, it selects one itself but only from the ones installed. If you don't have one installed, it can't select any and therefore shows you the error.

**Comment by Sh4d0wF1gh7** [comment]
Okay i installed NodeJS 6. No the installation works but with a Deprecation Warning:
Sass 3.5 will no longer support Ruby 1.9.3. Please Upgrade Ruby 2.0.0
I installed Ruby from the Jessie Sources.
During the installation output, a few js.coffee files was compilated, but no Sass files.
But the installation runs without further errors.

After Apache2 restart and surfing to the redmine i got a Ruby (Rack) application could not be started) error with: Permission denied - /var/www/redmine-3.3.0/public/plugin_assets/redmine_time_tracker/javascripts/validators.js (Errno::EACCES)

My complete plugins folder is owned by root, i set the redmine_time_tracker to www-data but no success...

**Comment by Sh4d0wF1gh7** [comment]
Ah sorry...
He said: /plugin_assets in the public folder...
Now it seems to work...
Great and thanks

**Comment by Sh4d0wF1gh7** [comment]
Sorry for my problems. Currently i tested to track one ticket and so far it works. Think i can track in parallel more tickets and should get an overview of the running tracker Time Log Link on the left top? In my case German "Zeiterfassung".
But this results just in an Internal error.
The logfile writes:
Completed 500 Internal Server Error in 320ms (ActiveRecord: 18.1ms)
NoMethodError (undefined method `strip' for ["time_logs.started_on DESC"]:Array):
  plugins/redmine_time_tracker/app/models/time_log_query.rb:59:in `logs'
  plugins/redmine_time_tracker/app/controllers/tt_overview_controller.rb:35:in `index'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
