### ISSUE TITLE
[wish] Textfield for entring Task in headline

### ISSUE THREAD

**Issue by xstable** [hicknhack-software/redmine_time_tracker#211]
I wish to have this Textfield:
![auswahl_021](https://cloud.githubusercontent.com/assets/1778068/19354594/9855093c-9167-11e6-8d7d-621a9b43204e.jpg)

here in the top-panel (as pulldown-layer) to be able to putt in a description directly :+1: 
![auswahl_022](https://cloud.githubusercontent.com/assets/1778068/19354695/f011bf1c-9167-11e6-9ba0-3473d307356c.jpg)

Currently I can start the tracker, but have to switch to Panel for Timetracks to add it.
Would be a really great enhencement.

**Comment by jume-dev** [comment]
If you press stop you will get an dialog asking you to add an activity (with the option to do so), but yeah you are right, we are gonna enhance the topmenu i guess, but not in this version anymore.
