### ISSUE TITLE
doesn't install with 3.3.1

### ISSUE THREAD

**Issue by biohazardxxx** [hicknhack-software/redmine_time_tracker#213]
Hi,

when I run command:
bundle exec rake redmine:plugins:migrate RAILS_ENV=production

I get an big error:
C:\Bitnami\redmine-3.3.1-0\apps\redmine\htdocs\plugins>bundle exec rake redmine:plugins:migrate NAME
=redmine_time_tracker VERSION=0 RAILS_ENV=production
(in C:/Bitnami/redmine-3.3.1-0/apps/redmine/htdocs)
DL is deprecated, please use Fiddle
Compiling coffeescript files:
---
rake aborted!
ExecJS::ProgramError: TypeError: Object doesn't support this property or method
C:/Bitnami/redmine-3.3.1-0/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/execjs-2.7.0/lib/execjs
/external_runtime.rb:39:in `exec'
.....

any idea what's wrong?

Best regards
-Bio

**Comment by jume-dev** [comment]
Sorry for the late reply, i somehow got no email for this issue.
As far as i can see this is the typical problem with coffeescript, please see #197.
Afaik you should check your coffee script source gem and either upgrade it to the newest version or downgrade it to 1.8.0
