### ISSUE TITLE
offer/search issue or project in context of selected issue or prioject

### ISSUE THREAD

**Issue by cforce** [hicknhack-software/redmine_time_tracker#99]
When i i wanna book time the plugin gets project list for user when typing into input field form project. After i selected the project i search for issue by typing issue id in issue input form. 
It would expect that onbly issues are offerend in drop down for this sklected project, because i can't book tome on an issue for an issue other project. If that issue must belong to rpoject and vice versa, the lookup shall vbe made in context of eahc other. Mean filter on issue for selcted project or filter and automtically select/replace project for this issue if issue is selected first instead of marking the wrong value red boxed.

**Comment by jume-dev** [comment]
Took a long time, but this is added in the rewrite.
